services:
  backend:
    image: renumate-backend:latest
    build:
      context: ./RenuMate.Api
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    restart: unless-stopped
  
  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: RenuMate
    volumes:
      - postgres_data:/var/lib/postgresql
    entrypoint: >
      sh -c "
      (sleep 5 && psql -U postgres -c 'CREATE DATABASE \"RenuMateHangfire\";') &
      /usr/local/bin/docker-entrypoint.sh postgres
      "
    restart: unless-stopped
    
  frontend:
    image: renumate-frontend:latest
    build:
      context: ./renumate-frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: unless-stopped

volumes:
  postgres_data:


